//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddChef
    {
        public int id { get; set; }
        public string contactno { get; set; }
        public string speciality { get; set; }
        public string specific { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> rsid { get; set; }
        public string picture { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
