//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddMenu()
        {
            this.Variations = new HashSet<Variation>();
        }
    
        public int id { get; set; }
        public string FoodName { get; set; }
        public string FoodType { get; set; }
        public string Category { get; set; }
        public Nullable<int> Price { get; set; }
        public string TimePrepation { get; set; }
        public string pic { get; set; }
        public Nullable<int> restid { get; set; }
        public Nullable<int> mirlevel { get; set; }
        public Nullable<double> rating { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variation> Variations { get; set; }
    }
}
