//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int id { get; set; }
        public string FName { get; set; }
        public string Ftype { get; set; }
        public string FCat { get; set; }
        public string FTimePrep { get; set; }
        public Nullable<double> FPrice { get; set; }
        public string TimeDate { get; set; }
        public string FImage { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> usrid { get; set; }
        public Nullable<int> retid { get; set; }
        public Nullable<int> FQuant { get; set; }
        public string UnitTag { get; set; }
        public string pickedtime { get; set; }
        public string pickeddate { get; set; }
        public string tbno { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
