//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetTable
    {
        public int id { get; set; }
        public string table_no { get; set; }
        public string table_image { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> tblrestid { get; set; }
        public string capacity { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
